python experiments.py 10
python experiments.py 10
python experiments.py 10
python experiments.py 10
python experiments.py 10
python experiments.py 10
python experiments.py 10
python experiments.py 10
python experiments.py 10
python experiments.py 10
python experiments.py 20
python experiments.py 20
python experiments.py 20
python experiments.py 20
python experiments.py 20
python experiments.py 20
python experiments.py 20
python experiments.py 20
python experiments.py 20
python experiments.py 20
python experiments.py 30
python experiments.py 30
python experiments.py 30
python experiments.py 30
python experiments.py 30
python experiments.py 30
python experiments.py 30
python experiments.py 30
python experiments.py 30
python experiments.py 30
python experiments.py 40
python experiments.py 40
python experiments.py 40
python experiments.py 40
python experiments.py 40
python experiments.py 40
python experiments.py 40
python experiments.py 40
python experiments.py 40
python experiments.py 40
python experiments(heuristic).py 200
python experiments(heuristic).py 200
python experiments(heuristic).py 200
python experiments(heuristic).py 200
python experiments(heuristic).py 200
python experiments(heuristic).py 200
python experiments(heuristic).py 200
python experiments(heuristic).py 200
python experiments(heuristic).py 200
python experiments(heuristic).py 200
python experiments(heuristic).py 1000
python experiments(heuristic).py 1000
python experiments(heuristic).py 1000
python experiments(heuristic).py 1000
python experiments(heuristic).py 1000
python experiments(heuristic).py 1000
python experiments(heuristic).py 1000
python experiments(heuristic).py 1000
python experiments(heuristic).py 1000
python experiments(heuristic).py 1000